services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    volumes:
      - ./nexus-data:/nexus-data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus.rule=Host(`nexus.phumlaniarendse.co.za`)"
      - "traefik.http.routers.nexus.entrypoints=websecure"
      - "traefik.http.routers.nexus.service=nexus"
      - "traefik.http.routers.nexus.tls=true"
      - "traefik.http.routers.nexus.tls.certresolver=staging"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
      - "traefik.docker.network=proxy-net"
    networks:
      - proxy-net

volumes:
  nexus-data:
    name: "nexus-data"

networks:
  proxy-net:
    name: "proxy-net"
    external: true
